spring:
  liquibase:
    change-log: 'classpath:db/migration/library-management-system-changelog.sql'
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library-management
    username: library-management-user
    password: development-password
    driverClassName: org.postgresql.Driver

server:
  port: ${PORT:8080}
  servlet:
    context-path: '/api'

---

spring:
  config:
    activate:
      on-profile: development

default:
  admin:
    name: 'Kaique Lucena'
    email: 'kaique@lucena.com'
    password: 'kaique123'