spring:
  liquibase:
    change-log: 'classpath:db/migration/library-management-system-changelog.sql'
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library-management
    username: library-management-user
    password: development-password
    driverClassName: org.postgresql.Driver

server:
  port: ${PORT:8080}
  servlet:
    context-path: '/api'

---

spring:
  config:
    activate:
      on-profile: development

app:
  admin:
    name: 'Kaique Lucena'
    email: 'kaique@lucena.com'
    password: 'kaique123'
  jwt:
    secret: '404D635166546A576E5A7234753777217A25432A462D4A614E645267556B58703273357638792F413F4428472B4B6250655368566D597133743677397A244326'